apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    name: hello-world-service
    app: hello-world-app
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 10080
    nodePort: 30080
  selector:
    name: hello-world-pod
    app: hello-world-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    name: hello-world-deployment
    app: hello-world-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-world-pod
      app: hello-world-app
  template:
    metadata:
      labels:
        name: hello-world-pod
        app: hello-world-app
    spec:
      containers:
      - name: hello-world
        image: tutum/hello-world
        ports:
        - containerPort: 80